#ifndef COEUR_H_INCLUDED
#define COEUR_H_INCLUDED

#define TOUTES_LED_CLIGNOTANTES
#define MODE_CHENILLE
#define LED_1_SUR_2_ALLUMEE
#define LED_1_SUR_3_ALLUMEE


#endif // COEUR_H_INCLUDED
