#ifndef MODULE_COEUR_H_INCLUDED
#define MODULE_COEUR_H_INCLUDED
#define TOUTES_LED_CLIGNOTANTES
#define MODE_CHENILLE
#define LED_1_SUR_2_ALLUMEE
#define LED_2_SUR_2_ALLUMEE



#endif // MODULE_COEUR_H_INCLUDED
