#ifndef PARAM_H_INCLUDED
#define PARAM_H_INCLUDED

#ifndef PARAM_H_INCLUDED
#define PARAM_H_INCLUDED

#define TOUTES_LED_CLIGNOTANTES
#endif

#define TOUTES_LED_CLIGNOTANTES
#define MODE_CHENILLE
#define LED_1_SUR_2_ALLUMEE
#define LED_1_SUR_3_ALLUMEE


#endif // PARAM_H_INCLUDED
